# Moldova Terrain Loader
# Generated from SRTM elevation data
# Size: 470 x 147 blocks
# Run this function from where you want the terrain origin

say Loading Moldova terrain (300 chunks)...

function terrain/chunk_0_0
function terrain/chunk_1_0
function terrain/chunk_2_0
function terrain/chunk_3_0
function terrain/chunk_4_0
function terrain/chunk_5_0
function terrain/chunk_6_0
function terrain/chunk_7_0
function terrain/chunk_8_0
function terrain/chunk_9_0
function terrain/chunk_10_0
function terrain/chunk_11_0
function terrain/chunk_12_0
function terrain/chunk_13_0
function terrain/chunk_14_0
function terrain/chunk_15_0
function terrain/chunk_16_0
function terrain/chunk_17_0
function terrain/chunk_18_0
function terrain/chunk_19_0
function terrain/chunk_20_0
function terrain/chunk_21_0
function terrain/chunk_22_0
function terrain/chunk_23_0
function terrain/chunk_24_0
function terrain/chunk_25_0
function terrain/chunk_26_0
function terrain/chunk_27_0
function terrain/chunk_28_0
function terrain/chunk_29_0
function terrain/chunk_0_1
function terrain/chunk_1_1
function terrain/chunk_2_1
function terrain/chunk_3_1
function terrain/chunk_4_1
function terrain/chunk_5_1
function terrain/chunk_6_1
function terrain/chunk_7_1
function terrain/chunk_8_1
function terrain/chunk_9_1
function terrain/chunk_10_1
function terrain/chunk_11_1
function terrain/chunk_12_1
function terrain/chunk_13_1
function terrain/chunk_14_1
function terrain/chunk_15_1
function terrain/chunk_16_1
function terrain/chunk_17_1
function terrain/chunk_18_1
function terrain/chunk_19_1
function terrain/chunk_20_1
function terrain/chunk_21_1
function terrain/chunk_22_1
function terrain/chunk_23_1
function terrain/chunk_24_1
function terrain/chunk_25_1
function terrain/chunk_26_1
function terrain/chunk_27_1
function terrain/chunk_28_1
function terrain/chunk_29_1
function terrain/chunk_0_2
function terrain/chunk_1_2
function terrain/chunk_2_2
function terrain/chunk_3_2
function terrain/chunk_4_2
function terrain/chunk_5_2
function terrain/chunk_6_2
function terrain/chunk_7_2
function terrain/chunk_8_2
function terrain/chunk_9_2
function terrain/chunk_10_2
function terrain/chunk_11_2
function terrain/chunk_12_2
function terrain/chunk_13_2
function terrain/chunk_14_2
function terrain/chunk_15_2
function terrain/chunk_16_2
function terrain/chunk_17_2
function terrain/chunk_18_2
function terrain/chunk_19_2
function terrain/chunk_20_2
function terrain/chunk_21_2
function terrain/chunk_22_2
function terrain/chunk_23_2
function terrain/chunk_24_2
function terrain/chunk_25_2
function terrain/chunk_26_2
function terrain/chunk_27_2
function terrain/chunk_28_2
function terrain/chunk_29_2
function terrain/chunk_0_3
function terrain/chunk_1_3
function terrain/chunk_2_3
function terrain/chunk_3_3
function terrain/chunk_4_3
function terrain/chunk_5_3
function terrain/chunk_6_3
function terrain/chunk_7_3
function terrain/chunk_8_3
function terrain/chunk_9_3
function terrain/chunk_10_3
function terrain/chunk_11_3
function terrain/chunk_12_3
function terrain/chunk_13_3
function terrain/chunk_14_3
function terrain/chunk_15_3
function terrain/chunk_16_3
function terrain/chunk_17_3
function terrain/chunk_18_3
function terrain/chunk_19_3
function terrain/chunk_20_3
function terrain/chunk_21_3
function terrain/chunk_22_3
function terrain/chunk_23_3
function terrain/chunk_24_3
function terrain/chunk_25_3
function terrain/chunk_26_3
function terrain/chunk_27_3
function terrain/chunk_28_3
function terrain/chunk_29_3
function terrain/chunk_0_4
function terrain/chunk_1_4
function terrain/chunk_2_4
function terrain/chunk_3_4
function terrain/chunk_4_4
function terrain/chunk_5_4
function terrain/chunk_6_4
function terrain/chunk_7_4
function terrain/chunk_8_4
function terrain/chunk_9_4
function terrain/chunk_10_4
function terrain/chunk_11_4
function terrain/chunk_12_4
function terrain/chunk_13_4
function terrain/chunk_14_4
function terrain/chunk_15_4
function terrain/chunk_16_4
function terrain/chunk_17_4
function terrain/chunk_18_4
function terrain/chunk_19_4
function terrain/chunk_20_4
function terrain/chunk_21_4
function terrain/chunk_22_4
function terrain/chunk_23_4
function terrain/chunk_24_4
function terrain/chunk_25_4
function terrain/chunk_26_4
function terrain/chunk_27_4
function terrain/chunk_28_4
function terrain/chunk_29_4
function terrain/chunk_0_5
function terrain/chunk_1_5
function terrain/chunk_2_5
function terrain/chunk_3_5
function terrain/chunk_4_5
function terrain/chunk_5_5
function terrain/chunk_6_5
function terrain/chunk_7_5
function terrain/chunk_8_5
function terrain/chunk_9_5
function terrain/chunk_10_5
function terrain/chunk_11_5
function terrain/chunk_12_5
function terrain/chunk_13_5
function terrain/chunk_14_5
function terrain/chunk_15_5
function terrain/chunk_16_5
function terrain/chunk_17_5
function terrain/chunk_18_5
function terrain/chunk_19_5
function terrain/chunk_20_5
function terrain/chunk_21_5
function terrain/chunk_22_5
function terrain/chunk_23_5
function terrain/chunk_24_5
function terrain/chunk_25_5
function terrain/chunk_26_5
function terrain/chunk_27_5
function terrain/chunk_28_5
function terrain/chunk_29_5
function terrain/chunk_0_6
function terrain/chunk_1_6
function terrain/chunk_2_6
function terrain/chunk_3_6
function terrain/chunk_4_6
function terrain/chunk_5_6
function terrain/chunk_6_6
function terrain/chunk_7_6
function terrain/chunk_8_6
function terrain/chunk_9_6
function terrain/chunk_10_6
function terrain/chunk_11_6
function terrain/chunk_12_6
function terrain/chunk_13_6
function terrain/chunk_14_6
function terrain/chunk_15_6
function terrain/chunk_16_6
function terrain/chunk_17_6
function terrain/chunk_18_6
function terrain/chunk_19_6
function terrain/chunk_20_6
function terrain/chunk_21_6
function terrain/chunk_22_6
function terrain/chunk_23_6
function terrain/chunk_24_6
function terrain/chunk_25_6
function terrain/chunk_26_6
function terrain/chunk_27_6
function terrain/chunk_28_6
function terrain/chunk_29_6
function terrain/chunk_0_7
function terrain/chunk_1_7
function terrain/chunk_2_7
function terrain/chunk_3_7
function terrain/chunk_4_7
function terrain/chunk_5_7
function terrain/chunk_6_7
function terrain/chunk_7_7
function terrain/chunk_8_7
function terrain/chunk_9_7
function terrain/chunk_10_7
function terrain/chunk_11_7
function terrain/chunk_12_7
function terrain/chunk_13_7
function terrain/chunk_14_7
function terrain/chunk_15_7
function terrain/chunk_16_7
function terrain/chunk_17_7
function terrain/chunk_18_7
function terrain/chunk_19_7
function terrain/chunk_20_7
function terrain/chunk_21_7
function terrain/chunk_22_7
function terrain/chunk_23_7
function terrain/chunk_24_7
function terrain/chunk_25_7
function terrain/chunk_26_7
function terrain/chunk_27_7
function terrain/chunk_28_7
function terrain/chunk_29_7
function terrain/chunk_0_8
function terrain/chunk_1_8
function terrain/chunk_2_8
function terrain/chunk_3_8
function terrain/chunk_4_8
function terrain/chunk_5_8
function terrain/chunk_6_8
function terrain/chunk_7_8
function terrain/chunk_8_8
function terrain/chunk_9_8
function terrain/chunk_10_8
function terrain/chunk_11_8
function terrain/chunk_12_8
function terrain/chunk_13_8
function terrain/chunk_14_8
function terrain/chunk_15_8
function terrain/chunk_16_8
function terrain/chunk_17_8
function terrain/chunk_18_8
function terrain/chunk_19_8
function terrain/chunk_20_8
function terrain/chunk_21_8
function terrain/chunk_22_8
function terrain/chunk_23_8
function terrain/chunk_24_8
function terrain/chunk_25_8
function terrain/chunk_26_8
function terrain/chunk_27_8
function terrain/chunk_28_8
function terrain/chunk_29_8
function terrain/chunk_0_9
function terrain/chunk_1_9
function terrain/chunk_2_9
function terrain/chunk_3_9
function terrain/chunk_4_9
function terrain/chunk_5_9
function terrain/chunk_6_9
function terrain/chunk_7_9
function terrain/chunk_8_9
function terrain/chunk_9_9
function terrain/chunk_10_9
function terrain/chunk_11_9
function terrain/chunk_12_9
function terrain/chunk_13_9
function terrain/chunk_14_9
function terrain/chunk_15_9
function terrain/chunk_16_9
function terrain/chunk_17_9
function terrain/chunk_18_9
function terrain/chunk_19_9
function terrain/chunk_20_9
function terrain/chunk_21_9
function terrain/chunk_22_9
function terrain/chunk_23_9
function terrain/chunk_24_9
function terrain/chunk_25_9
function terrain/chunk_26_9
function terrain/chunk_27_9
function terrain/chunk_28_9
function terrain/chunk_29_9

say Terrain generation complete!